name: Check links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "15 07 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Symlink uploads
        run: |
          ln -s ./static/uploads ./content/uploads
          ln -s ./content ./cabforum.org

      - name: Restore lychee cache
        uses: actions/cache@v3
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.9.1
        with:
          args: --base . --cache --max-cache-age 1d --no-progress ./content

      - name: Find Link Checker Issue
        if: env.lychee_exit_code != 0
        uses: micalevisk/last-issue-action@v2
        with:
          state: open
          labels: |
            link checker

      - name: Create or update Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          issue-number: "${{ steps.link-checker-issue.outputs.issue-number }}"
          content-filepath: ./lychee/out.md
          labels: link checker, automated issue
