name: Check links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "15 07 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.121.2
    steps:
      ## Build website
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          hugo \
            --minify \
            --baseURL "/"
      - name: Create search index
        run: npx -y pagefind --site public

        ## Check links
      - name: Restore lychee cache
        uses: actions/cache@v3
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.9.1
        with:
          args: --base ./public --cache --max-cache-age 1d --no-progress ./public

      - name: Find Link Checker Issue
        if: env.lychee_exit_code != 0
        uses: micalevisk/last-issue-action@v2
        with:
          state: open
          labels: |
            link checker
      
      ## Create/update issue
      - name: Create or update Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          issue-number: "${{ steps.link-checker-issue.outputs.issue-number }}"
          content-filepath: ./lychee/out.md
          labels: link checker, automated issue
